In [15]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
import geo

Latitude: 49.2608724, Longitude: -123.113952
{'type': 'node', 'id': 505751618, 'name': '7-Eleven', 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.2829841, 'longitude': -123.115166}
{'type': 'node', 'id': 513053415, 'name': '7-Eleven', 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.2788081, 'longitude': -123.116272}
{'type': 'node', 'id': 638747932, 'name': '7-Eleven', 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.2760946, 'longitude': -123.127478}
{'type': 'node', 'id': 860814204, 'name': '7-Eleven', 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.2657274, 'longitude': -123.1202276}
{'type': 'node', 'id': 892055470, 'name': 'Circle K', 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.2633455, 'longitude': -123.136476}
{'type': 'node', 'id': 998584755, 'name': 'Hye Park Express', 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.260983, 'longitude': -123.1157472}
{'type': 'node', 'id': 1209173521, 'name': 'Martway', 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.2743145, 'longitude': -123.1221035}
{'type': 'node', 'id': 1329276217, 'name': 'Circle K', 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.272646, 'longitude': -123.149985}
{'type': 'node', 'id': 1418439984, 'name': '7-Eleven', 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.2764951, 'longitude': -123.1216802}
{'type': 'node', 'id': 1723476080, 'name': 'Los Tapatios Imports', 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.2628323, 'longitude': -123.1031554}
{'type': 'node', 'id': 1769817334, 'name': "Aling Mary's Store", 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.2612353, 'longitude': -123.1007516}
{'type': 'node', 'id': 1769919864, 'name': 'Main Convenience Store', 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.2623745, 'longitude': -123.1012494}
{'type': 'node', 'id': 1796612723, 'name': 'Vancouver Main Terminal', 'amenity': 'bus_station', 'shop': 'N/A', 'latitude': 49.2735297, 'longitude': -123.097864}
{'type': 'node', 'id': 1798834303, 'name': 'Anchor Point Montesorri', 'amenity': 'school', 'shop': 'N/A', 'latitude': 49.2769886, 'longitude': -123.1306637}
{'type': 'node', 'id': 2321115305, 'name': '7-Eleven', 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.2884384, 'longitude': -123.122991}
{'type': 'node', 'id': 2485918695, 'name': 'Mart Way', 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.2803888, 'longitude': -123.131473}
{'type': 'node', 'id': 2998231878, 'name': 'One Stop Shop', 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.279649, 'longitude': -123.123989}
{'type': 'node', 'id': 3108751084, 'name': 'Granville Food Market', 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.2781932, 'longitude': -123.1242984}
{'type': 'node', 'id': 3601697960, 'name': '7-Eleven', 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.2765465, 'longitude': -123.115167}
{'type': 'node', 'id': 3708806648, 'name': 'Foodness Supermarket', 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.279303, 'longitude': -123.1213597}
{'type': 'node', 'id': 3711299532, 'name': '7-Eleven', 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.2888268, 'longitude': -123.139684}
{'type': 'node', 'id': 3719407591, 'name': 'Victory Food Market', 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.2822519, 'longitude': -123.109283}
{'type': 'node', 'id': 3725404708, 'name': 'Simon Fraser University', 'amenity': 'university', 'shop': 'N/A', 'latitude': 49.2824032, 'longitude': -123.1085513}
{'type': 'node', 'id': 3729617704, 'name': "Oscar's Smoke Shop", 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.2811016, 'longitude': -123.124385}
{'type': 'node', 'id': 3729617774, 'name': 'Terrace Smoke Shop', 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.2819564, 'longitude': -123.123078}
{'type': 'node', 'id': 3731201011, 'name': 'Denman Market', 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.2899137, 'longitude': -123.1375662}
{'type': 'node', 'id': 3734942642, 'name': 'Burrard Corner Store', 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.2783946, 'longitude': -123.130591}
{'type': 'node', 'id': 3734942644, 'name': 'Pattison High School', 'amenity': 'school', 'shop': 'N/A', 'latitude': 49.2809046, 'longitude': -123.124905}
{'type': 'node', 'id': 3738438877, 'name': '7-Eleven', 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.2793271, 'longitude': -123.122593}
{'type': 'node', 'id': 3743635243, 'name': 'Urban Choice Market', 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.277439, 'longitude': -123.12696}
{'type': 'node', 'id': 3753945310, 'name': 'Al-Madina General Store', 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.2833921, 'longitude': -123.113138}
{'type': 'node', 'id': 3753957572, 'name': 'My Convenience Store', 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.283786, 'longitude': -123.1118241}
{'type': 'node', 'id': 3755319078, 'name': 'Seymour Mini Mart', 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.2840683, 'longitude': -123.1134863}
{'type': 'node', 'id': 3755319079, 'name': 'Cornerstone Community College', 'amenity': 'school', 'shop': 'N/A', 'latitude': 49.2835785, 'longitude': -123.1147762}
{'type': 'node', 'id': 3755320481, 'name': 'N/A', 'amenity': 'school', 'shop': 'N/A', 'latitude': 49.2833602, 'longitude': -123.1145916}
{'type': 'node', 'id': 3786978105, 'name': 'Neotown', 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.2794688, 'longitude': -123.107847}
{'type': 'node', 'id': 3789321343, 'name': 'Vancity Corner Store', 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.2815564, 'longitude': -123.1024544}
{'type': 'node', 'id': 3789851064, 'name': 'Jubilee Smoke & Things', 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.2862492, 'longitude': -123.1165796}
{'type': 'node', 'id': 3931566491, 'name': '7-Eleven', 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.2802877, 'longitude': -123.1074}
{'type': 'node', 'id': 3940285759, 'name': 'Smoke & Food Market', 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.280083, 'longitude': -123.1208635}
{'type': 'node', 'id': 3940617014, 'name': 'Express News', 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.2828522, 'longitude': -123.107023}
{'type': 'node', 'id': 4261863289, 'name': 'EF International Language Centre Vancouver', 'amenity': 'school', 'shop': 'N/A', 'latitude': 49.2786617, 'longitude': -123.114003}
{'type': 'node', 'id': 4323354089, 'name': 'Cherry Market', 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.2868379, 'longitude': -123.1286149}
{'type': 'node', 'id': 4390230579, 'name': 'Circle K', 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.2818491, 'longitude': -123.116762}
{'type': 'node', 'id': 4390232009, 'name': 'Enjoy Canada', 'amenity': 'school', 'shop': 'N/A', 'latitude': 49.2827302, 'longitude': -123.115289}
{'type': 'node', 'id': 4454235293, 'name': 'ILAC', 'amenity': 'school', 'shop': 'N/A', 'latitude': 49.2888774, 'longitude': -123.121472}
{'type': 'node', 'id': 4731543620, 'name': 'Express News', 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.2801298, 'longitude': -123.1066456}
{'type': 'node', 'id': 4731545724, 'name': 'Yoko Yaya', 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.2803551, 'longitude': -123.1063062}
{'type': 'node', 'id': 4824054122, 'name': 'collège Educacentre', 'amenity': 'school', 'shop': 'N/A', 'latitude': 49.264166, 'longitude': -123.1239861}
{'type': 'node', 'id': 4842937822, 'name': 'Vancouver English Centre', 'amenity': 'school', 'shop': 'N/A', 'latitude': 49.2773179, 'longitude': -123.1171798}
{'type': 'node', 'id': 4888589421, 'name': 'Light House Labs', 'amenity': 'school', 'shop': 'N/A', 'latitude': 49.2819085, 'longitude': -123.108188}
{'type': 'node', 'id': 4993915651, 'name': 'Princess Market', 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.2813527, 'longitude': -123.0916951}
{'type': 'node', 'id': 5004169223, 'name': 'Your Dollar Store', 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.2763124, 'longitude': -123.1208}
{'type': 'node', 'id': 5010472966, 'name': 'Adler University', 'amenity': 'university', 'shop': 'N/A', 'latitude': 49.2837148, 'longitude': -123.1140662}
{'type': 'node', 'id': 5062597029, 'name': 'Sherry Convenience', 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.2630707, 'longitude': -123.1019377}
{'type': 'node', 'id': 5062659359, 'name': 'VGC International College', 'amenity': 'school', 'shop': 'N/A', 'latitude': 49.2844007, 'longitude': -123.115654}
{'type': 'node', 'id': 5162084604, 'name': 'UBC Robson Square', 'amenity': 'university', 'shop': 'N/A', 'latitude': 49.2824292, 'longitude': -123.121177}
{'type': 'node', 'id': 5241750021, 'name': 'Global Village English Centers', 'amenity': 'school', 'shop': 'N/A', 'latitude': 49.2773055, 'longitude': -123.116045}
{'type': 'node', 'id': 5773634784, 'name': 'Central Gourmet Market', 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.2708632, 'longitude': -123.1480527}
{'type': 'node', 'id': 6018363188, 'name': "Stop 'n Go", 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.274455, 'longitude': -123.126735}
{'type': 'node', 'id': 6505003628, 'name': 'Konbiniya Japan Centre', 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.2863788, 'longitude': -123.127863}
{'type': 'node', 'id': 6552017237, 'name': 'Dank Mart', 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.2844311, 'longitude': -123.125345}
{'type': 'node', 'id': 6859044407, 'name': 'Vancouver Film School', 'amenity': 'school', 'shop': 'N/A', 'latitude': 49.2832374, 'longitude': -123.107818}
{'type': 'node', 'id': 7231937859, 'name': 'Yaletown Express', 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.2740907, 'longitude': -123.120278}
{'type': 'node', 'id': 7367692555, 'name': "Dean's Food Store", 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.2678717, 'longitude': -123.135268}
{'type': 'node', 'id': 8402215131, 'name': 'Sino Bright School BC', 'amenity': 'school', 'shop': 'N/A', 'latitude': 49.2842936, 'longitude': -123.1095896}
{'type': 'node', 'id': 8487554546, 'name': 'Carrall Supermarket', 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.2822673, 'longitude': -123.104131}
{'type': 'node', 'id': 8942482418, 'name': 'KGS Convenience', 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.281522, 'longitude': -123.0986155}
{'type': 'node', 'id': 9670437429, 'name': 'Circle K', 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.2815956, 'longitude': -123.133376}
{'type': 'node', 'id': 9906266382, 'name': 'City Park Express', 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.2920168, 'longitude': -123.134383}
{'type': 'node', 'id': 9948546503, 'name': 'Town Pantry', 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.2945579, 'longitude': -123.1181002}
{'type': 'node', 'id': 9981992784, 'name': 'Freshco Food Mart', 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.2893278, 'longitude': -123.129092}
{'type': 'node', 'id': 10013460009, 'name': 'Davie Market', 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.2866152, 'longitude': -123.140494}
{'type': 'node', 'id': 10013470488, 'name': 'Circle K', 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.2863772, 'longitude': -123.140724}
{'type': 'node', 'id': 10013825632, 'name': 'Martway', 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.2874517, 'longitude': -123.1412634}
{'type': 'node', 'id': 10052755932, 'name': 'Northeastern University — Vancouver', 'amenity': 'university', 'shop': 'N/A', 'latitude': 49.2805472, 'longitude': -123.1158219}
{'type': 'node', 'id': 10250014802, 'name': 'Quickstop', 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.2586199, 'longitude': -123.114831}
{'type': 'node', 'id': 10314988415, 'name': 'Main Mini Mart', 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.2824255, 'longitude': -123.0998807}
{'type': 'node', 'id': 11057576996, 'name': 'Jong Wah Company', 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.2802229, 'longitude': -123.097556}
{'type': 'node', 'id': 11062762228, 'name': 'Washington Community Market', 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.2815486, 'longitude': -123.1004676}
{'type': 'node', 'id': 11447439072, 'name': 'Easy Day Store', 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.275085, 'longitude': -123.1326542}
{'type': 'node', 'id': 11461417183, 'name': 'Alexander Academy', 'amenity': 'school', 'shop': 'N/A', 'latitude': 49.2826985, 'longitude': -123.1153061}
{'type': 'node', 'id': 11463588087, 'name': 'Canada Royal High School', 'amenity': 'school', 'shop': 'N/A', 'latitude': 49.2641592, 'longitude': -123.1238069}
{'type': 'node', 'id': 11506478042, 'name': 'N/A', 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.2807839, 'longitude': -123.0993865}
{'type': 'node', 'id': 11742811569, 'name': 'Canadian College of Technology and Business', 'amenity': 'school', 'shop': 'N/A', 'latitude': 49.2767138, 'longitude': -123.1156499}
{'type': 'node', 'id': 11762237833, 'name': 'Main Food Store', 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.2732926, 'longitude': -123.1003446}
{'type': 'node', 'id': 11885120272, 'name': 'Vancouver Independent School for Science and Technology', 'amenity': 'school', 'shop': 'N/A', 'latitude': 49.263407, 'longitude': -123.1381407}
{'type': 'node', 'id': 11965660297, 'name': 'Harbour News', 'amenity': 'N/A', 'shop': 'convenience', 'latitude': 49.2849258, 'longitude': -123.1122173}
{'type': 'node', 'id': 12737106811, 'name': 'The Westside Schools – Miniversity', 'amenity': 'university', 'shop': 'N/A', 'latitude': 49.2766137, 'longitude': -123.1185482}
Distance from house to 7-Eleven: 0.40 km
Distance from house to 7-Eleven: 0.54 km
Distance from house to 7-Eleven: 0.88 km
Distance from house to 7-Eleven: 1.89 km
Distance from house to Circle K: 2.44 km
Distance from house to Hye Park Express: 2.44 km
Distance from house to Martway: 0.94 km
Distance from house to Circle K: 2.40 km
Distance from house to 7-Eleven: 0.69 km
Distance from house to Los Tapatios Imports: 2.55 km
Distance from house to Aling Mary's Store: 2.79 km
Distance from house to Main Convenience Store: 2.66 km
Distance from house to Vancouver Main Terminal: 1.95 km
Distance from house to Anchor Point Montesorri: 0.96 km
Distance from house to 7-Eleven: 0.66 km
Distance from house to Mart Way: 0.82 km
Distance from house to One Stop Shop: 0.41 km
Distance from house to Granville Food Market: 0.57 km
Distance from house to 7-Eleven: 0.79 km
Distance from house to Foodness Supermarket: 0.38 km
Distance from house to 7-Eleven: 1.54 km
Distance from house to Victory Food Market: 0.83 km
Distance from house to Simon Fraser University: 0.88 km
Distance from house to Oscar's Smoke Shop: 0.32 km
Distance from house to Terrace Smoke Shop: 0.19 km
Distance from house to Denman Market: 1.46 km
Distance from house to Burrard Corner Store: 0.86 km
Distance from house to Pattison High School: 0.36 km
Distance from house to 7-Eleven: 0.40 km
Distance from house to Urban Choice Market: 0.74 km
Distance from house to Al-Madina General Store: 0.55 km
Distance from house to My Convenience Store: 0.66 km
Distance from house to Seymour Mini Mart: 0.54 km
Distance from house to Cornerstone Community College: 0.44 km
Distance from house to N/A: 0.45 km
Distance from house to Neotown: 1.00 km
Distance from house to Vancity Corner Store: 1.33 km
Distance from house to Jubilee Smoke & Things: 0.50 km
Distance from house to 7-Eleven: 1.00 km
Distance from house to Smoke & Food Market: 0.29 km
Distance from house to Express News: 0.99 km
Distance from house to EF International Language Centre Vancouver: 0.66 km
Distance from house to Cherry Market: 0.74 km
Distance from house to Circle K: 0.30 km
Distance from house to Enjoy Canada: 0.39 km
Distance from house to ILAC: 0.69 km
Distance from house to Express News: 1.06 km
Distance from house to Yoko Yaya: 1.08 km
Distance from house to collège Educacentre: 2.07 km
Distance from house to Vancouver English Centre: 0.65 km
Distance from house to Light House Labs: 0.91 km
Distance from house to Princess Market: 2.11 km
Distance from house to Your Dollar Store: 0.71 km
Distance from house to Adler University: 0.49 km
Distance from house to Sherry Convenience: 2.57 km
Distance from house to VGC International College: 0.41 km
Distance from house to UBC Robson Square: 0.05 km
Distance from house to Global Village English Centers: 0.69 km
Distance from house to Central Gourmet Market: 2.38 km
Distance from house to Stop 'n Go: 1.02 km
Distance from house to Konbiniya Japan Centre: 0.66 km
Distance from house to Dank Mart: 0.39 km
Distance from house to Vancouver Film School: 0.94 km
Distance from house to Yaletown Express: 0.96 km
Distance from house to Dean's Food Store: 1.96 km
Distance from house to Sino Bright School BC: 0.83 km
Distance from house to Carrall Supermarket: 1.20 km
Distance from house to KGS Convenience: 1.61 km
Distance from house to Circle K: 0.93 km
Distance from house to City Park Express: 1.43 km
Distance from house to Town Pantry: 1.33 km
Distance from house to Freshco Food Mart: 0.96 km
Distance from house to Davie Market: 1.50 km
Distance from house to Circle K: 1.51 km
Distance from house to Martway: 1.58 km
Distance from house to Northeastern University — Vancouver: 0.43 km
Distance from house to Quickstop: 2.71 km
Distance from house to Main Mini Mart: 1.51 km
Distance from house to Jong Wah Company: 1.70 km
Distance from house to Washington Community Market: 1.47 km
Distance from house to Easy Day Store: 1.21 km
Distance from house to Alexander Academy: 0.39 km
Distance from house to Canada Royal High School: 2.07 km
Distance from house to N/A: 1.56 km
Distance from house to Canadian College of Technology and Business: 0.76 km
Distance from house to Main Food Store: 1.81 km
Distance from house to Vancouver Independent School for Science and Technology: 2.49 km
Distance from house to Harbour News: 0.66 km
Distance from house to The Westside Schools – Miniversity: 0.69 km

In [16]:
data = pd.read_csv('data_bc.csv')
dataBC = data[data['addressRegion'] == 'BC']
dataBC = dataBC.sort_values(by='addressLocality')
dataBC.head()

C:\Users\17787\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (42,93,259) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,streetAddress,addressLocality,addressRegion,postalCode,latitude,longitude,description,price,priceCurrency,property-beds,...,MLS Area Minor,View,Foundation Details,SqFt Range,Building Area Source,Buyer Agent Designation,Lot Measurement,Lot Size Source,Topography,Current Financing
4337,"6263 MULLIGAN DRIVE, 100 Mile House, BC V0K2E3",100 Mile House,BC,V0K2E3,51.584053,-121.143606,* PREC - Personal Real Estate Corporation. WA...,647000.0,CAD,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4739,"6470 MERCER ROAD, 100 Mile House, BC V0K2E3",100 Mile House,BC,V0K2E3,51.611912,-121.236554,This tidy 2 bed / 2 bath manufactured home is ...,425000.0,CAD,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3148,"6847 FAWN LK AC01 ROAD, 100 Mile House, BC V0K1X1",100 Mile House,BC,V0K1X1,51.554452,-120.981004,When only the best will do!! Ultimate log home...,1100000.0,CAD,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
618,"825 SCOTT ROAD, 100 Mile House, BC V0K2E0",100 Mile House,BC,V0K2E0,51.634147,-121.301281,* PREC - Personal Real Estate Corporation. Me...,559000.0,CAD,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2216,"4741 TELQUA DRIVE, 100 Mile House, BC V0K2Z0",100 Mile House,BC,V0K2Z0,51.747026,-121.347015,* PREC - Personal Real Estate Corporation. No...,399900.0,CAD,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
dataBC = dataBC.filter([
    'streetAddress',
    'addressLocality',
    'addressRegion',
    'postalCode',
    'latitude',
    'longitude',
    'price',
    'property-beds',
    'property-baths',
    'property-sqft',
    'Year Built',
    'Area',
    'Garage',
    'Parking Spaces',
    'Property Type', #Agricultural, Condo, Condo/Townhouse, Duplex, Manufactured Home, Mobile Home, MultiFamily, Single Family, Townhome, Vacant Land
    'Square Footage',
    'Waterfront',
    ])
data_bc_single_family = dataBC[dataBC['Property Type'] == 'Single Family']

In [18]:
metro_vancouver_cities = [
    "Vancouver", "Burnaby", "Richmond", "Surrey", "Coquitlam",
    "North Vancouver", "West Vancouver", "New Westminster",
    "Delta", "Port Coquitlam", "Port Moody", "Langley"
]
data_bc_single_family = data_bc_single_family[data_bc_single_family['addressLocality'].isin(metro_vancouver_cities)]
sample = data_bc_single_family.head()
sample

,streetAddress,addressLocality,addressRegion,postalCode,latitude,longitude,price,property-beds,property-baths,property-sqft,Year Built,Area,Garage,Parking Spaces,Property Type,Square Footage,Waterfront
7409,"51 N SEA AVENUE, Burnaby, BC V5B 1K4",Burnaby,BC,V5B 1K4,49.284733,-122.979824,2188000.0,5.0,3.0,"2,515",NaN,NaN,NaN,NaN,Single Family,"2,515 SQFT",NaN
12098,"7815 ALLMAN STREET, Burnaby, BC V5E 2A9",Burnaby,BC,V5E 2A9,49.235055,-122.950665,3999000.0,8.0,9.0,"6,399",NaN,NaN,NaN,NaN,Single Family,"6,399 SQFT",NaN
6686,"8274 WEDGEWOOD STREET, Burnaby, BC V3N 1C4",Burnaby,BC,V3N 1C4,49.231928,-122.927040,1868000.0,3.0,1.0,"1,775",NaN,NaN,NaN,NaN,Single Family,"1,775 SQFT",NaN
12124,"6555 DENBIGH AVENUE, Burnaby, BC V5H 3R7",Burnaby,BC,V5H 3R7,49.224338,-122.984424,3990000.0,5.0,4.0,"2,736",NaN,NaN,NaN,NaN,Single Family,"2,736 SQFT",NaN
4441,"7088 HALIFAX STREET, Burnaby, BC V5A 1L8",Burnaby,BC,V5A 1L8,49.267710,-122.956486,2998888.0,6.0,5.0,"4,946",NaN,NaN,NaN,NaN,Single Family,"4,946 SQFT",NaN

In [19]:
# data_bc_single_family.sort_values(by='Price', ascending=False)
data_bc_single_family.to_csv('data_bc_1.csv')

In [20]:
lat_lon_array = sample[['latitude', 'longitude']].to_numpy()
lat_lon_array

array([[  49.2847328, -122.9798237],
       [  49.2350546, -122.950665 ],
       [  49.2319281, -122.9270398],
       [  49.2243379, -122.9844235],
       [  49.2677095, -122.9564857]])

In [24]:
# write code here for using geo.haversine() to get individual address distances


#k so we need the "reference" location 
#not sure what we are mesuring here 
reference_lat = 49.2827  #sample latitude for Vancouver
reference_lon = -123.1207  #sample longitude for Vancouver

#go over each property to find the distance to the reference point 
data_bc_single_family['distance_to_reference'] = data_bc_single_family.apply(lambda row: geo.haversine(reference_lat, reference_lon, row['latitude'], row['longitude']), axis=1 )

# show first few rows with the calculated distances
data_bc_single_family[['streetAddress', 'addressLocality', 'price', 'distance_to_reference']].head()

,streetAddress,addressLocality,price,distance_to_reference
7409,"51 N SEA AVENUE, Burnaby, BC V5B 1K4",Burnaby,2188000.0,10.220818
12098,"7815 ALLMAN STREET, Burnaby, BC V5E 2A9",Burnaby,3999000.0,13.428771
6686,"8274 WEDGEWOOD STREET, Burnaby, BC V3N 1C4",Burnaby,1868000.0,15.145970
12124,"6555 DENBIGH AVENUE, Burnaby, BC V5H 3R7",Burnaby,3990000.0,11.829666
4441,"7088 HALIFAX STREET, Burnaby, BC V5A 1L8",Burnaby,2998888.0,12.029219

The code below is for normalizing data once we have it all cleaned up. We can ignore it for now and come back to it once we have clean data with all our columns

In [ ]:
features = ['Price', 'Bedrooms', 'Bathrooms', 'Acreage', 'Square Footage']
scaler = MinMaxScaler()

data_scaled = sample.copy()
data_scaled[features] = scaler.fit_transform(sample[features])

data_scaled["Price"] = 1 - data_scaled['Price']
data_scaled['Garage'] = data_scaled['Garage'].map({'Yes': 1, 'No': 0})
data_scaled['Parking'] = data_scaled['Parking'].map({'Yes': 1, 'No': 0})
data_scaled.head()

In [ ]:
score_features = [
    'Price',
    'Bedrooms',
    'Bathrooms',
    'Square Footage',
    'Acreage',
    'Garage',
    'Parking'
]

weights = np.array([1/len(score_features)] * len(score_features))
data_scored = data_scaled.copy()
data_scored['Score'] = data_scaled[score_features].dot(weights)
data_scored.sort_values(by='Score', ascending=False, inplace=True)
data_scored

In [41]:
#loading the census data 
#load census data into a df

# Load the census data into a DataFrame
data = pd.read_csv('CensusProfile2021.csv')
data = pd.read_csv('census_data.csv', header=0)  # Set the first row as header

data.columns = ['Topic', 'Characteristic', 'Total']  # Rename columns

population_data = data[data['Topic'] == 'Population and dwellings']
print(population_data)

                      Topic                                 Characteristic  \
1  Population and dwellings                               Population, 2021
2  Population and dwellings                               Population, 2016
3  Population and dwellings     Population percentage change, 2016 to 2021
4  Population and dwellings                        Total private dwellings
5  Population and dwellings  Private dwellings occupied by usual residents
6  Population and dwellings        Population density per square kilometre
7  Population and dwellings                 Land area in square kilometres

       Total
1    5000879
2    4648055
3        7.6
4    2211694
5    2041834
6        5.4
7  920686.55